# Generated by Django 4.0.3 on 2022-03-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='usersImages'),
        ),
    ]
