# Generated by Django 4.0.3 on 2022-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0011_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('message_date_time', models.DateTimeField()),
            ],
        ),
    ]
