# Generated by Django 4.0.3 on 2022-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0013_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_date_time', models.DateTimeField()),
                ('product_id', models.IntegerField()),
                ('choice_mark', models.BooleanField(default=False)),
                ('ad_likes', models.IntegerField()),
                ('ad_dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('owner', models.IntegerField(null=True)),
                ('buyer', models.IntegerField(null=True)),
                ('item_availablity', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=500)),
                ('image1', models.ImageField(upload_to='productImages')),
                ('image2', models.ImageField(blank=True, upload_to='productImages')),
                ('image3', models.ImageField(blank=True, upload_to='productImages')),
                ('image4', models.ImageField(blank=True, upload_to='productImages')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='productImages'),
        ),
    ]
