# Generated by Django 4.0.3 on 2022-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabit', '0015_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='usersImages'),
        ),
    ]
